### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by dah366** [CIVICS/OpenCollab#1]
Is this the best organization for the paper?

**Comment by dazzaji** [comment]
Good question - I'll take a look.  I think it is not.  After all, we just
rocked that out for a GitHub demo, right?  ;-)

---

   |   Dazza Greenwood, JD
   |   CIVICS.com, Founder & Principal
   |   MIT Media Lab, Visiting Scientist
   |     Vmail: 617.500.3644
   |     Email: dazza@CIVICS.com
   |     Biz: http://CIVICS.com
   |     MIT: https://law.MIT.edu
   |     Me: DazzaGreenwood.com
   |     Twitter: @DazzaGreenwood
   |     Google+: google.com/+DazzaGreenwood
   |     LinkedIn: linkedin.com/in/DazzaGreenwood
   |     GitHub: github.com/DazzaGreenwood/Interface
   |     Postal: P.O. Box 425845 Cambridge, MA  02142
   | _ _ _ _ _ _ _ _ _ _ _ _ _ _
