### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by dah366** [CIVICS/OpenCollab#3]
![image2](https://cloud.githubusercontent.com/assets/11131821/6365331/eba13f1c-bc83-11e4-9d5c-f1b738a541ca.jpeg)

![image1](https://cloud.githubusercontent.com/assets/11131821/6365333/f0bb57f8-bc83-11e4-8b99-ddad8a26282a.jpeg)

**Comment by dazzaji** [comment]
Hey - interesting to note that the orientation of the pics is correct when clicked on but sideways as thumbnails embedded in issue.  Good to know!

**Comment by dazzaji** [comment]
This was a demo of images.  Case closed, counsel!
